title: DataUniverse Blog
description: Insights on Data Analytics and Big Data
baseurl: ""       # leave blank for root domain
url: "https://datauniver.se"
theme: minima     # or another supported theme
author:
  name: Tugce Ozdeger
